### ISSUE TITLE
'wireguard__restart_interface' is undefined with wg-config

### ISSUE THREAD

**Issue by sas1024** [githubixx/ansible-role-wireguard#211] opened 2024-10-30 14:13 UTC
Hi!

I upgraded from 8.4.0 to 17.0.0 role version and give following error:
When I try to use `wg-config` tag to deploy only configuration changes, I've got error `'wireguard__restart_interface' is undefined`.

As workaround I added this to groups variables file:
```
wireguard__restart_interface: false
```

After this, role with tag `wg-config` works again.

**Comment by githubixx** [comment] 2024-10-30 20:39
Honestly the tags are not very well tested. I guess I shouldn't have them implemented at all. Nevertheless I guess the problem is that [this task](https://github.com/githubixx/ansible-role-wireguard/blob/master/tasks/main.yml#L39-L48) is missing the `wg-config` tag. Without there is no default value for the internal `wireguard__restart_interface` variable. I try to fix that in the next release.

**Comment by githubixx** [comment] 2024-11-06 20:33
Should be fixed by https://github.com/githubixx/ansible-role-wireguard/pull/213

**Closed by githubixx** 2024-11-06 20:33 UTC
